[package]
name = "pointrain-filter"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
kiddo = "3.0.0"
pointrain-core.workspace = true

[dev-dependencies]
approx.workspace = true
