[package]
name = "pc-read"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
pointrain = { workspace = true, features = ["io", "rerun"] }
rerun = { version = "0.10.1", features = ["native_viewer"] }
structopt = "0.3.26"
