[package]
name = "pcd_read"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
anyhow.workspace = true
pointrain = { workspace = true, features = ["io", "rerun"] }
rerun = { workspace = true, features = ["native_viewer"] }
structopt = "0.3"
