name: Test

on:
  schedule:
    - cron: "0 13 * * 6"

  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    strategy:
      fail-fast: false

      matrix:
        rust:
          - 1.73.0
          - stable
          - beta
          - nightly

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}

      - name: Check
        run: cargo build --workspace --all-features --exclude pc-read

      - name: Test
        run: cargo test --workspace --all-features --exclude pc-read

  audit:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install Tools
        run: cargo install cargo-audit cargo-outdated

      - name: Outdated
        run: cargo outdated --root-deps-only --exit-code 1

      - name: Audit
        run: cargo audit || true
